apiVersion: v1
kind: ReplicationController
metadata:
  name: replicacontrol
spec:
  replicas: 2
  selector:
    app: prod
  template:
    metadata:
      labels:
        app: prod
    spec:
      containers:
      - name: x3m555
        image: x3m5555/k8s
        ports:
        - containerPort: 80
