---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-index
data:
  index.php: |

    <?php
    $ip_server = $_SERVER['SERVER_ADDR'];
        
    echo "<h1>Hello from Kubernetes</h1><br>";

    echo "the $enviroment  IP address is: $ip_server", "<br><p>"

    ?>
 
...
