apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-pv
spec:
  capacity: 
    storage: 50M
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /tmp/nginx
