#!/bin/bash
echo "--------------------START----------------------"
yum -y update
yum -y install httpd
echo "<html><body>
    <section class="congratulations">
        <h1>Congratulations brother!</h1>
        <p>Your AWS Elastic Beanstalk <em>PHP</em> application is now running on your own dedicated environment in the AWS&nbsp;Cloud</p>
        <p>You are running PHP version <?= phpversion() ?></p>
        <p>zalupa</p>
    </section><html>"
sudo service httpd start
chkconfig httpd on
echo "UserData executed on $(date)" >> /var/www/html/log.txt
echo "-------------------FINISH--------------------"