apiVersion: v1
kind: ReplicationController
metadata:
  name: replicacontrol
spec:
  replicas: 2
  selector:
    app: fort
  template:
    metadata:
      labels:
        app: fort
    spec:
      containers:
      - image: nginx:alpine
        name: web-server
        volumeMounts:
         - name: html
           mountPath: /usr/share/nginx/html
           readOnly: true
        ports:
        - containerPort: 80
          protocol: TCP
      - image: jlowin/git-sync 
        name: git-sync-volume
        volumeMounts:
        - name: html
          mountPath: /git
        env:
        - name: GIT_SYNC_REPO  
          value: https://github.com/andgit7/proxy-HPV.git
        - name: GIT_SYNC_DEST
          value: /git
        - name: GIT_SYNC_WAIT
          value: "10"
        - name: GIT_SYNC_BRANCH
          value: main  
            
      volumes:
      - name: html
        emptyDir: {}
#        gitRepo:
#          repository: https://github.com/andgit7/proxy-HPV.git
#          revision: main
#          directory: .  