apiVersion: v1
kind: Service
metadata:
  name: my-service-ext-ips
spec:
 selector:
   app: my-app
 ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
 externalIPs:
 - 192.168.56.40