---
apiVersion: v1
kind: Service
metadata:
  name: my-service-headless
spec:
  selector:
    app: my-app
  clusterIP: None
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP